### ISSUE TITLE
add MPI_Type_create_hindexed, MPI_Type_create_struct

### ISSUE THREAD

**Issue by xantares** [ssciwr/FakeMPI#14]
would it be possible to add these two ?

**Comment by dokempf** [comment]
Hey @xantares, thanks for checking out the library. If you provide an implementation, I will gladly include it into the "experimental" portion of the library ([Header](https://github.com/ssciwr/FakeMPI/blob/main/include/experimental_unimpi.h), [Lib](https://github.com/ssciwr/FakeMPI/blob/main/lib/experimental_unimpi.c)). I added this experimental part to separate the mature parts from PetSc from less mature additions needed for specific applications. The same holds for your additions in #12 and #13.

When you use FakeMPI in a project, I will also gladly feature it somewhere in the README as an example project. Just let me know about your use case.

**Comment by dokempf** [comment]
This is merged.
